version: '3.7'

services:
  database_challenge:
    image: postgres
    container_name: database_challenge
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: fin_api
    restart: always
    ports:
      - 4444:4444
    volumes:
      - .:/usr/app
    links:
      - database_challenge
    depends_on:
      - database_challenge

volumes:
  pgdata:
    driver: local
